version: '3.9'
services:
  testing_db:
    image: postgres:latest
    container_name: db_test_db
    environment:
      - POSTGRES_USER=${DB_USER:-admin}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-password}
      - POSTGRES_DB=${DB_NAME:-test_db}
      - DATABASE_HOST=${DB_HOST:-localhost}
    ports:
      - '5432:5432'
    volumes:
      - testing_db:/var/lib/postgresql/data
volumes:
  testing_db:

networks:
  default:
    driver: bridge